"""Iniciar migracion

Revision ID: 370036bd53b4
Revises: 
Create Date: 2025-09-20 16:53:28.665764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370036bd53b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procesador', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('camara', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bateria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pantalla', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('memoria', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('memoria')
        batch_op.drop_column('pantalla')
        batch_op.drop_column('bateria')
        batch_op.drop_column('camara')
        batch_op.drop_column('procesador')

    # ### end Alembic commands ###
