name: 🔄 Sync Branches with Main

on:
  schedule:
    - cron: '0 6 * * *'   # Cada día a las 6 AM UTC
  workflow_dispatch:       # Permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into all branches
        run: |
          for branch in $(git for-each-ref --format '%(refname:short)' refs/remotes/origin/ | grep -v main); do
            git checkout $branch
            git merge origin/main --no-edit || true
            git push origin $branch || true
          done
